Exploration de la donnée

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataproject.txt', sep=";", decimal=',', encoding='UTF-8')

In [3]:
df.head(10)

,ZIBZIN,IDAvisAutorisAtionCheque,MontAnt,DAteTrAnsAction,CodeDecision,VerifiAnceCPT1,VerifiAnceCPT2,VerifiAnceCPT3,D2CB,ScoringFP1,...,TAuxImpNB_CPM,EcArtNumCheq,NbrMAgAsin3J,DiffDAteTr1,DiffDAteTr2,DiffDAteTr3,CA3TRetMtt,CA3TR,Heure,FlAgImpAye
0,A034010041908012010710730,71051532,40.17,2016-03-21 07:47:38,0,1,1,1,535,0.000000,...,21.834061,0,1,4.0,4.0,4.0,40.17,0.0,28058,0
1,A035010041908006493331734,71051533,20.00,2016-03-21 08:04:57,0,0,0,0,358,0.000000,...,12.586532,0,1,4.0,4.0,4.0,20.00,0.0,29097,0
2,A013010003908005150136747,71051534,35.00,2016-03-21 08:06:45,0,0,0,0,199,0.000000,...,39.274924,0,1,4.0,4.0,4.0,35.00,0.0,29205,0
3,A013010041908025639221029,71051536,20.00,2016-03-21 08:11:38,0,0,0,0,38,0.000000,...,39.274924,0,1,4.0,4.0,4.0,20.00,0.0,29498,0
4,A013010003908005556100283,71051538,20.00,2016-03-21 08:17:11,0,0,0,0,26,0.000000,...,39.274924,0,1,4.0,4.0,4.0,20.00,0.0,29831,0
5,A007010278908891620264901,71051539,35.09,2016-03-21 08:17:26,0,0,0,0,459,0.000000,...,35.523979,0,1,4.0,4.0,4.0,35.09,0.0,29846,0
6,A056010003908116850002378,71051541,60.00,2016-03-21 08:19:56,0,0,0,0,500,0.000000,...,12.586532,0,1,4.0,4.0,4.0,60.00,0.0,29996,0
7,A034013506908085106167163,71051542,120.00,2016-03-21 08:20:42,0,1,1,1,389,0.308483,...,21.834061,0,1,4.0,4.0,4.0,120.00,0.0,30042,0
8,A056015589908090385895930,71051544,59.25,2016-03-21 08:21:04,0,1,1,1,538,0.000000,...,12.586532,0,1,4.0,4.0,4.0,59.25,0.0,30064,0
9,A056015589908093500453310,71051548,17.00,2016-03-21 08:22:56,0,0,0,0,13,0.000000,...,12.586532,0,1,4.0,4.0,4.0,17.00,0.0,30176,0

In [13]:
df.shape

(2231369, 23)

In [16]:
df.iloc[:,9:].describe(include='all')

,ScoringFP1,ScoringFP2,ScoringFP3,TAuxImpNb_RB,TAuxImpNB_CPM,EcArtNumCheq,NbrMAgAsin3J,DiffDAteTr1,DiffDAteTr2,DiffDAteTr3,CA3TRetMtt,CA3TR,Heure,FlAgImpAye
count,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06,2.231369e+06
mean,3.100542e+00,6.882686e-01,1.769416e-01,3.286594e+01,3.256122e+01,6.724334e+03,1.034200e+00,3.947808e+00,4.234163e+00,4.266234e+00,6.683475e+01,6.917041e+00,5.347306e+04,2.804108e-03
std,3.047480e+01,9.336748e+00,5.662696e-01,9.774278e+01,3.475789e+01,1.742520e+05,1.862585e-01,1.078915e+00,5.510923e-01,4.643674e-01,8.929606e+01,3.550385e+01,1.200173e+04,5.287955e-02
min,0.000000e+00,-4.969986e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,4.745370e-04,1.365741e-03,1.000000e-02,0.000000e+00,1.336000e+03,0.000000e+00
25%,5.874265e-03,-2.869431e+00,1.179973e-03,0.000000e+00,1.390821e+01,0.000000e+00,1.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,2.792000e+01,0.000000e+00,4.248500e+04,0.000000e+00
50%,1.543502e-02,0.000000e+00,2.131271e-03,1.547988e+01,2.526529e+01,0.000000e+00,1.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.732000e+01,0.000000e+00,5.488200e+04,0.000000e+00
75%,1.370299e-01,5.289664e+00,1.533859e-02,3.460208e+01,3.927492e+01,0.000000e+00,1.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,8.130000e+01,0.000000e+00,6.390700e+04,0.000000e+00
max,1.680000e+04,4.702998e+01,1.839140e+01,1.000000e+04,7.142857e+02,9.993474e+06,1.000000e+01,5.000000e+00,5.000000e+00,5.000000e+00,1.698534e+04,1.060000e+04,8.256400e+04,1.000000e+00

In [6]:
df.dtypes

ZIBZIN                       object
IDAvisAutorisAtionCheque      int64
MontAnt                     float64
DAteTrAnsAction              object
CodeDecision                  int64
VerifiAnceCPT1                int64
VerifiAnceCPT2                int64
VerifiAnceCPT3                int64
D2CB                          int64
ScoringFP1                  float64
ScoringFP2                  float64
ScoringFP3                  float64
TAuxImpNb_RB                float64
TAuxImpNB_CPM               float64
EcArtNumCheq                  int64
NbrMAgAsin3J                  int64
DiffDAteTr1                 float64
DiffDAteTr2                 float64
DiffDAteTr3                 float64
CA3TRetMtt                  float64
CA3TR                       float64
Heure                         int64
FlAgImpAye                    int64
dtype: object

In [7]:
impaye = df[df['FlAgImpAye'] == 1]
impaye.shape

(6257, 23)

In [8]:
impaye

,ZIBZIN,IDAvisAutorisAtionCheque,MontAnt,DAteTrAnsAction,CodeDecision,VerifiAnceCPT1,VerifiAnceCPT2,VerifiAnceCPT3,D2CB,ScoringFP1,...,TAuxImpNB_CPM,EcArtNumCheq,NbrMAgAsin3J,DiffDAteTr1,DiffDAteTr2,DiffDAteTr3,CA3TRetMtt,CA3TR,Heure,FlAgImpAye
49,A075004265908008772124369,71051662,45.07,2016-03-21 08:44:19,0,1,2,3,49,0.000000,...,43.753038,4,3,1.535231,2.655104,4.0,125.21,80.14,31459,1
245,A026010096908801944136301,71077583,50.01,2016-03-22 10:10:08,0,1,2,3,1,0.000000,...,35.523979,0,1,5.000000,5.000000,5.0,50.01,0.00,36608,1
321,A012010003908132050370361,71077780,211.14,2016-03-22 10:14:19,0,1,1,1,125,0.048261,...,9.451796,0,1,4.000000,4.000000,4.0,211.14,0.00,36859,1
473,A075002135908004172315358,71078249,4.34,2016-03-22 10:24:29,0,0,0,0,290,0.014966,...,0.000000,0,1,4.000000,4.000000,4.0,4.34,0.00,37469,1
1496,A045010041908062118821033,71081166,15.30,2016-03-22 11:23:40,0,0,0,0,518,0.001867,...,258.823529,0,1,4.000000,4.000000,4.0,15.30,0.00,41020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2231066,A038010002908260082985326,76191853,36.89,2016-10-19 19:42:35,0,0,0,0,539,0.007605,...,15.654352,0,1,4.000000,4.000000,4.0,36.89,0.00,70955,1
2231102,A075008315908204350454253,76191923,183.40,2016-10-19 19:45:59,0,1,3,3,49,0.138624,...,24.301337,7,2,1.338727,2.182350,4.0,453.54,270.14,71159,1
2231258,A013010096908829320871101,76192205,242.98,2016-10-19 20:10:15,0,1,1,1,74,0.218901,...,39.274924,0,1,4.000000,4.000000,4.0,242.98,0.00,72615,1
2231275,A006019106908043610265597,76192241,134.47,2016-10-19 20:16:06,0,1,1,1,87,0.067201,...,25.265285,11,2,2.125208,2.139248,4.0,161.65,27.18,72966,1
2231320,A087010041908008749420027,76192329,23.43,2016-10-19 20:33:51,0,0,0,0,301,0.005988,...,0.000000,0,1,4.000000,4.000000,4.0,23.43,0.00,74031,1

In [9]:
impaye.describe(include='all')

,ZIBZIN,IDAvisAutorisAtionCheque,MontAnt,DAteTrAnsAction,CodeDecision,VerifiAnceCPT1,VerifiAnceCPT2,VerifiAnceCPT3,D2CB,ScoringFP1,...,TAuxImpNB_CPM,EcArtNumCheq,NbrMAgAsin3J,DiffDAteTr1,DiffDAteTr2,DiffDAteTr3,CA3TRetMtt,CA3TR,Heure,FlAgImpAye
count,6257,6.257000e+03,6257.000000,6257,6257.000000,6257.000000,6257.000000,6257.000000,6257.000000,6257.000000,...,6257.000000,6.257000e+03,6257.000000,6257.000000,6257.000000,6257.000000,6257.000000,6257.000000,6257.000000,6257.0
unique,4069,NaN,NaN,6254,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,A013010041908020729891229,NaN,NaN,2016-06-03 12:53:03,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,14,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,7.372501e+07,94.557721,NaN,0.049385,0.582228,0.762506,1.043791,120.252357,13.129692,...,40.543897,4.913774e+03,1.113952,3.462059,4.132642,4.308389,125.447465,30.889744,55993.042832,1.0
std,NaN,1.461851e+06,133.659270,NaN,0.326215,0.736553,1.035116,1.660143,174.550080,60.269539,...,46.146348,1.356109e+05,0.427206,1.662598,1.004134,0.696478,183.762486,103.232060,11768.679965,0.0
min,NaN,7.105166e+07,3.170000,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000e+00,1.000000,0.000324,0.003507,0.016412,4.000000,0.000000,1402.000000,1.0
25%,NaN,7.249057e+07,31.160000,NaN,0.000000,0.000000,0.000000,0.000000,1.000000,0.011909,...,21.834061,0.000000e+00,1.000000,2.167292,4.000000,4.000000,38.340000,0.000000,45944.000000,1.0
50%,NaN,7.379739e+07,50.630000,NaN,0.000000,0.000000,0.000000,0.000000,13.000000,0.186288,...,26.478376,0.000000e+00,1.000000,4.000000,4.000000,4.000000,69.880000,0.000000,57660.000000,1.0
75%,NaN,7.498143e+07,103.240000,NaN,0.000000,1.000000,1.000000,2.000000,198.000000,3.941429,...,41.356493,1.000000e+00,1.000000,5.000000,5.000000,5.000000,143.130000,23.110000,65860.000000,1.0
max,NaN,7.619233e+07,3825.610000,NaN,3.000000,9.000000,12.000000,18.000000,551.000000,905.000000,...,714.285714,7.423270e+06,7.000000,5.000000,5.000000,5.000000,5156.190000,3775.720000,79798.000000,1.0